### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by bendschs** [sot-tech/LottieConverter#1]
is there a small guide somewhere how to install this on debian?

i was able to build the libraries, the tarred binary does not seem to be working and the git repo gives me the following result after trying to "make": 

>  make
> "make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
> make[1]: Verzeichnis „/home/osmc/Lottie/test/LottieConverter-r0.1“ wird betreten
> "make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux/lottieconverter
> make[2]: Verzeichnis „/home/osmc/Lottie/test/LottieConverter-r0.1“ wird betreten
> mkdir -p build/Debug/GNU-Linux
> rm -f "build/Debug/GNU-Linux/lottie_export.o.d"
> g++    -c -g -std=c++14 -MMD -MP -MF "build/Debug/GNU-Linux/lottie_export.o.d" -o build/Debug/GNU-Linux/lottie_export.o lottie_export.cpp
> In file included from lottie_export.cpp:27:0:
> lottie_export.h:36:21: fatal error: rlottie.h: Datei oder Verzeichnis nicht gefunden
>  #include <rlottie.h>
>                      ^
> compilation terminated.
> nbproject/Makefile-Debug.mk:66: die Regel für Ziel „build/Debug/GNU-Linux/lottie_export.o“ scheiterte
> make[2]: *** [build/Debug/GNU-Linux/lottie_export.o] Fehler 1
> make[2]: Verzeichnis „/home/osmc/Lottie/test/LottieConverter-r0.1“ wird verlassen
> nbproject/Makefile-Debug.mk:59: die Regel für Ziel „.build-conf“ scheiterte
> make[1]: *** [.build-conf] Fehler 2
> make[1]: Verzeichnis „/home/osmc/Lottie/test/LottieConverter-r0.1“ wird verlassen
> nbproject/Makefile-impl.mk:39: die Regel für Ziel „.build-impl“ scheiterte
> make: *** [.build-impl] Fehler 2

**Comment by sot-tech** [comment]
You should refer to origin rlottie build instructions: https://github.com/Samsung/rlottie#building-lottie 
Maby I'll add full build instructions, if it necessary

**Comment by sot-tech** [comment]
Added build [howto](https://github.com/Eramde/LottieConverter#Build) and modified makefile to support additional flags, please pull fix, hope, i'll help.
